- SEQUENCE FOR EMPLOYEE_ID
---------------------------------------------------------

    CREATE SEQUENCE EMPLOYEE _ID_SEQ
         START WITH 1
         INCREMENT BY 1
         ORDER;

--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE EMPLOYEE   
   (	  EMPLOYEE_ID   NUMBER(25,0), 
	  EMP_FIRST_NAME   VARCHAR2(60)  , 
	  EMP_LAST_NAME VARCHAR2(60)  , 
	  EMP_EMAIL  VARCHAR2(255)  ,
	  EMP_PASSWORD  VARCHAR2(255)  , 
	  DATE_OF_JOINING  DATE , 
	  ADDRESS_ID VARCHAR2(255),
	  ROLE_ID VARCHAR2(255) 
   )


--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

	ALTER TABLE EMPLOYEE   MODIFY (  EMPLOYEE_ID   CONSTRAINT EMPLOYEE_ID_NOT_NULL  NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   ADD CONSTRAINT EMPLOYEE_ID_PK   PRIMARY KEY (  EMPLOYEE_ID  )
  	USING INDEX  ENABLE;
	ALTER TABLE EMPLOYEE   MODIFY (  EMP_FIRST_NAME   CONSTRAINT EMP_FIRST_NAME_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  EMP_LAST_NAME   CONSTRAINT EMP_LAST_NAME_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  DATE_OF_JOINING   CONSTRAINT DATE_OF_JOINING_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  EMP_EMAIL   CONSTRAINT EMP_EMAIL_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  EMP_PASSWORD   CONSTRAINT EMP_PASSWORD_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  ADDRESS_ID   CONSTRAINT ADDRESS_ID_NOT_NULL   NOT NULL ENABLE);
 	ALTER TABLE EMPLOYEE   MODIFY (  ROLE_ID   CONSTRAINT ROLE_ID_NOT_NULL   NOT NULL ENABLE);
 	
 	--ADDITION OF UNIQUE KEY CONSTRAINT TO EMAIL AND PASSWORD
 	ALTER TABLE EMPLOYEE  ADD CONSTRAINT EMP_EMAIL  UNIQUE (  EMP_EMAIL  )
  USING INDEX  ENABLE;
 
 
--------------------------------------------------------
--  DDL for Package PCKG_EMPLOYEE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE PCKG_EMPLOYEE   AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */
    

    PROCEDURE INSERT_EMPLOYEE(
        vEMPLOYEE_ID IN EMPLOYEE.EMPLOYEE_ID%type,
        vEMP_FIRST_NAME IN EMPLOYEE.EMP_FIRST_NAME%type,
        vEMP_LAST_NAME IN EMPLOYEE.EMP_LAST_NAME%type,
        vEMP_EMAIL IN EMPLOYEE.EMP_EMAIL %type,
        vEMP_PASSWORD IN EMPLOYEE.EMP_PASSWORD%type,
        vDATE_OF_JOINING IN EMPLOYEE.DATE_OF_JOINING%type,
        vADDRESS_ID IN EMPLOYEE.ADDRESS_ID%type,
        vROLE_ID IN EMPLOYEE.ROLE_ID%type
    );
    
    PROCEDURE UPDATE_CAR(
       vEMPLOYEE_ID IN EMPLOYEE.EMPLOYEE_ID%type,
        vEMP_FIRST_NAME IN EMPLOYEE.EMP_FIRST_NAME%type,
        vEMP_LAST_NAME IN EMPLOYEE.EMP_LAST_NAME%type,
        vEMP_EMAIL IN EMPLOYEE.EMP_EMAIL %type,
        vEMP_PASSWORD IN EMPLOYEE.EMP_PASSWORD%type,
        vDATE_OF_JOINING IN EMPLOYEE.DATE_OF_JOINING%type,
        vADDRESS_ID IN EMPLOYEE.ADDRESS_ID%type,
        vROLE_ID IN EMPLOYEE.ROLE_ID%type
    );
    
    
    PROCEDURE DELETE_EMPLOYEE (
        vEMPLOYEE_ID IN EMPLOYEE.EMPLOYEE_ID%type
    );
    
END PCKG_EMPLOYEE;

/

 
