- SEQUENCE FOR EMPLOYEE_ID
---------------------------------------------------------

    CREATE SEQUENCE EMPLOYEE _ID_SEQ
         START WITH 1
         INCREMENT BY 1
         ORDER;

--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE EMPLOYEE   
   (	  EMPLOYEE_ID   NUMBER(25,0), 
	  EMP_FIRST_NAME   VARCHAR2(60)  , 
	  EMP_LAST_NAME VARCHAR2(60)  , 
	  EMP_EMAIL  VARCHAR2(255)  ,
	  EMP_PASSWORD  VARCHAR2(255)  , 
	  DATE_OF_JOINING  DATE , 
	  ADDRESS_ID VARCHAR2(255),
	  ROLE_ID VARCHAR2(255) 
   )


--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

	ALTER TABLE EMPLOYEE   MODIFY (  EMPLOYEE_ID   CONSTRAINT EMPLOYEE_ID_NOT_NULL  NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   ADD CONSTRAINT EMPLOYEE_ID_PK   PRIMARY KEY (  EMPLOYEE_ID  )
  	USING INDEX  ENABLE;
	ALTER TABLE EMPLOYEE   MODIFY (  EMP_FIRST_NAME   CONSTRAINT EMP_FIRST_NAME_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  EMP_LAST_NAME   CONSTRAINT EMP_LAST_NAME_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  DATE_OF_JOINING   CONSTRAINT DATE_OF_JOINING_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  EMP_EMAIL   CONSTRAINT EMP_EMAIL_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  EMP_PASSWORD   CONSTRAINT EMP_PASSWORD_NOT_NULL   NOT NULL ENABLE);
	ALTER TABLE EMPLOYEE   MODIFY (  ADDRESS_ID   CONSTRAINT ADDRESS_ID_NOT_NULL   NOT NULL ENABLE);
 	ALTER TABLE EMPLOYEE   MODIFY (  ROLE_ID   CONSTRAINT ROLE_ID_NOT_NULL   NOT NULL ENABLE);
 