SET SERVEROUTPUT ON;

CREATE OR REPLACE EDITIONABLE PACKAGE PCKG_PARKING AS
    PROCEDURE CHECK_AND_RETURN_PARKING_ID(
        vPARKING_ID OUT PARKING.PARKING_ID%type,
        vADDRESS_ID IN ADDRESS.ADDRESS_ID%type
    );
END PCKG_PARKING;
/

CREATE OR REPLACE EDITIONABLE PACKAGE BODY PCKG_PARKING AS
    PROCEDURE CHECK_AND_RETURN_PARKING_ID(
        vPARKING_ID OUT PARKING.PARKING_ID%type,
        vADDRESS_ID IN ADDRESS.ADDRESS_ID%type
    ) AS
    vCount NUMBER(5) DEFAULT 0;
    vCount2 NUMBER(5) DEFAULT 0;
    ex_INVALID_ADDRESS EXCEPTION;
    BEGIN
        SELECT COUNT(*) INTO vCount FROM ADDRESS WHERE ADDRESS_ID = TRIM(vADDRESS_ID) and ADDRESS_TYPE = 'PARKING';
        IF vCount != 1 THEN
            RAISE ex_INVALID_ADDRESS;
        END IF;
        SELECT COUNT(*) INTO vCount2 FROM PARKING WHERE ADDRESS_ID = vADDRESS_ID;
        IF vCount2 < 1 THEN
            INSERT INTO PARKING(PARKING_ID,ADDRESS_ID)
            VALUES (
                PARKING_ID_SEQ.NEXTVAL,
                vADDRESS_ID
            );
        END IF;
        SELECT PARKING_ID INTO vPARKING_ID FROM PARKING WHERE ADDRESS_ID = TRIM(vADDRESS_ID);
    EXCEPTION
        WHEN ex_INVALID_ADDRESS THEN
            dbms_output.put_line('ADDRESS ID IS INVALID OR DO NOT EXIST');
    END CHECK_AND_RETURN_PARKING_ID;
END PCKG_PARKING;
/
