
SELECT USER FROM DUAL;

--------------------------------------
--          ROLES
--------------------------------------
    CREATE ROLE APP_OWNER;
    CREATE ROLE DEVELOPER;
    CREATE ROLE TESTER;
    CREATE ROLE ANALYST;
    CREATE ROLE SERVICE;
    CREATE ROLE SECURITY;

---------------------------------------
---         APP_OWNER
---------------------------------------
    GRANT  CONNECT, CREATE SESSION to APP_OWNER;
    GRANT CREATE ANY TABLE TO APP_OWNER;
    GRANT ALL ON ADDRESS to APP_OWNER;
    GRANT ALL ON BOOKING to APP_OWNER;
    GRANT ALL ON CAR_CATEGORY to APP_OWNER;
    GRANT ALL ON CAR_LISTING to APP_OWNER;
    GRANT ALL ON CAR_REGISTRATION to APP_OWNER;
    GRANT ALL ON CITY to APP_OWNER;
    GRANT ALL ON COUNTRY to APP_OWNER;
    GRANT ALL ON EMPLOYEE to APP_OWNER;
    GRANT ALL ON PARKING to APP_OWNER;
    GRANT ALL ON ROLE to APP_OWNER;
    GRANT ALL ON STATE to APP_OWNER;
    GRANT ALL ON TRANSACTION to APP_OWNER;
    GRANT ALL ON USERS to APP_OWNER;
    
    GRANT ALL ON PCKG_CAR_CATEGORY TO APP_OWNER;
    GRANT ALL ON PCKG_CAR_LISTING TO APP_OWNER;
    GRANT ALL ON PCKG_CITY TO APP_OWNER;
    GRANT ALL ON PCKG_COUNTRY TO APP_OWNER;
    GRANT ALL ON PCKG_EMPLOYEE TO APP_OWNER; 
    GRANT ALL ON PCKG_PARKING TO APP_OWNER;
    GRANT ALL ON PCKG_PARKING_EXT TO APP_OWNER;
    GRANT ALL ON PCKG_ROLE TO APP_OWNER;
    GRANT ALL ON PCKG_STATE TO APP_OWNER;
    GRANT ALL ON PCKG_USERS TO APP_OWNER;
    GRANT ALL ON PKG_ADDRESS TO APP_OWNER;
    GRANT ALL ON PKG_BOOKING TO APP_OWNER;
    GRANT ALL ON PKG_CAR_REGISTER TO APP_OWNER;
    GRANT ALL ON PKG_TRANSACTION TO APP_OWNER;

    -- GRANT ALL ON ANALYST_VIEW TO APP_OWNER;
    -- GRANT ALL ON SUPPORT_VIEW TO APP_OWNER;
    -- GRANT ALL ON AUDIT_VIEW TO APP_OWNER;
---------------------------------------
---         DEVELOPER
---------------------------------------
    GRANT CONNECT, CREATE SESSION TO DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON ADDRESS to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON BOOKING to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CAR_CATEGORY to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CAR_LISTING to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CAR_REGISTRATION to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CITY to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON COUNTRY to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON EMPLOYEE to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON PARKING to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON STATE to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON TRANSACTION to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON USERS to DEVELOPER;
    
    GRANT ALL ON PCKG_CAR_CATEGORY TO DEVELOPER;
    GRANT ALL ON PCKG_CAR_LISTING TO DEVELOPER;
    GRANT ALL ON PCKG_CITY TO DEVELOPER;
    GRANT ALL ON PCKG_COUNTRY TO DEVELOPER;
    GRANT ALL ON PCKG_EMPLOYEE TO DEVELOPER; 
    GRANT ALL ON PCKG_PARKING TO DEVELOPER;
    GRANT ALL ON PCKG_PARKING_EXT TO DEVELOPER;
    GRANT ALL ON PCKG_STATE TO DEVELOPER;
    GRANT ALL ON PCKG_USERS TO DEVELOPER;
    GRANT ALL ON PKG_ADDRESS TO DEVELOPER;
    GRANT ALL ON PKG_BOOKING TO DEVELOPER;
    GRANT ALL ON PKG_CAR_REGISTER TO DEVELOPER;
    GRANT ALL ON PKG_TRANSACTION TO DEVELOPER;

    -- GRANT ALL ON ANALYST_VIEW TO APP_OWNER;
    -- GRANT ALL ON SUPPORT_VIEW TO APP_OWNER;
    -- GRANT ALL ON AUDIT_VIEW TO APP_OWNER;

---------------------------------------
---         TESTER
---------------------------------------
    GRANT CONNECT, CREATE SESSION to TESTER;
    GRANT SELECT, INSERT, UPDATE ON ADDRESS to TESTER;
    GRANT SELECT, INSERT, UPDATE ON BOOKING to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CAR_CATEGORY to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CAR_LISTING to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CAR_REGISTRATION to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CITY to TESTER;
    GRANT SELECT, INSERT, UPDATE ON COUNTRY to TESTER;
    GRANT SELECT, INSERT, UPDATE ON EMPLOYEE to TESTER;
    GRANT SELECT, INSERT, UPDATE ON PARKING to TESTER;
    GRANT SELECT, INSERT, UPDATE ON STATE to TESTER;
    GRANT SELECT, INSERT, UPDATE ON TRANSACTION to TESTER;
    GRANT SELECT, INSERT, UPDATE ON USERS to TESTER;
    
    GRANT EXECUTE ON PCKG_CAR_CATEGORY TO TESTER;
    GRANT EXECUTE ON PCKG_CAR_LISTING TO TESTER;
    GRANT EXECUTE ON PCKG_CITY TO TESTER;
    GRANT EXECUTE ON PCKG_COUNTRY TO TESTER;
    GRANT EXECUTE ON PCKG_EMPLOYEE TO TESTER; 
    GRANT EXECUTE ON PCKG_PARKING TO TESTER;
    GRANT EXECUTE ON PCKG_PARKING_EXT TO TESTER;
    GRANT EXECUTE ON PCKG_STATE TO TESTER;
    GRANT EXECUTE ON PCKG_USERS TO TESTER;
    GRANT EXECUTE ON PKG_ADDRESS TO TESTER;
    GRANT EXECUTE ON PKG_BOOKING TO TESTER;
    GRANT EXECUTE ON PKG_CAR_REGISTER TO TESTER;
    GRANT EXECUTE ON PKG_TRANSACTION TO TESTER;

    -- GRANT ALL ON ANALYST_VIEW TO TESTER;
    -- GRANT ALL ON SUPPORT_VIEW TO TESTER;
    -- GRANT ALL ON AUDIT_VIEW TO TESTER;
---------------------------------------
---  ANALYST 
---------------------------------------
    GRANT  CONNECT, CREATE SESSION to ANALYST;
    -- GRANT SELECT ON ANALYST_VIEW TO ANALYST;

---------------------------------------
---         SERVICE
---------------------------------------
    GRANT CONNECT, CREATE SESSION to SERVICE;
    GRANT EXECUTE ON PCKG_CAR_CATEGORY TO SERVICE;
    GRANT EXECUTE ON PCKG_CAR_LISTING TO SERVICE;
    GRANT EXECUTE ON PCKG_CITY TO SERVICE;
    GRANT EXECUTE ON PCKG_COUNTRY TO SERVICE;
    GRANT EXECUTE ON PCKG_EMPLOYEE TO SERVICE; 
    GRANT EXECUTE ON PCKG_PARKING TO SERVICE;
    GRANT EXECUTE ON PCKG_PARKING_EXT TO SERVICE;
    GRANT EXECUTE ON PCKG_STATE TO SERVICE;
    GRANT EXECUTE ON PCKG_USERS TO SERVICE;
    GRANT EXECUTE ON PKG_ADDRESS TO SERVICE;
    GRANT EXECUTE ON PKG_BOOKING TO SERVICE;
    GRANT EXECUTE ON PKG_CAR_REGISTER TO SERVICE;
    GRANT EXECUTE ON PKG_TRANSACTION TO SERVICE;

---------------------------------------
---  SECURITY
---------------------------------------
    GRANT CONNECT, CREATE SESSION to SECURITY;
    -- GRANT SELECT ON AUDIT_VIEW TO SECURITY;
    
----------------------------------------
--              USERS
----------------------------------------
    --APP_OWNER
    CREATE USER YASH IDENTIFIED BY Root1234567890; 
    --DEVELOPER
    CREATE USER DEEP IDENTIFIED BY Root1234567890;
    --TESTER
    CREATE USER SETHU IDENTIFIED BY Root1234567890;
    --ANALYST
    CREATE USER NOOR IDENTIFIED BY Root1234567890;
    --SERVICE
    CREATE USER SAI IDENTIFIED BY Root1234567890;
    --AUDIT
    CREATE USER VIVEK IDENTIFIED BY Root1234567890;



-----------------------------------------
-- ######################################
-----------------------------------------

-----------------------------------------
-- ROLES - USERS
-----------------------------------------

    GRANT APP_OWNER TO YASH;
    GRANT DEVELOPER TO DEEP;
    GRANT TESTER TO SETHU;
    GRANT ANALYST TO NOOR;
    GRANT SERVICE TO SAI;
    GRANT SECURITY TO VIVEK;

-----------------------------------------

    -- SELECT * FROM session_roles;
    
    -- SELECT * FROM user_role_privs;
    -- SELECT * FROM role_sys_privs where ROLE IN ('APP_OWNER','DEVELOPER','TESTER','ANALYST','SERVICE','SECURITY');
    -- SELECT * FROM role_tab_privs where ROLE IN ('APP_OWNER','DEVELOPER','TESTER','ANALYST','SERVICE','SECURITY');
    
    -- select * from ALL_TABLES where OWNER = 'ADMIN';
    -- select * from DBA_ROLE_PRIVS where grantee = 'ADMIN';
    
    -- SELECT * FROM dba_role_privs where GRANTED_ROLE IN ('ADMIN', 'APP_OWNER', 'DEVELOPER', 'TESTER', 'ANALYST', 'SERVICE', 'SECURITY');
