
SELECT USER FROM DUAL;

--------------------------------------
--          ROLES
--------------------------------------
    CREATE ROLE OWNER;
    CREATE ROLE DEVELOPER;
    CREATE ROLE TESTER;
    CREATE ROLE ANALYST;
    CREATE ROLE SERVICE;

---------------------------------------
---         APP_OWNER
---------------------------------------
    GRANT  CONNECT, CREATE SESSION to APP_OWNER;
    GRANT CREATE ANY TABLE TO APP_OWNER;
    GRANT ALL ON ADDRESS to APP_OWNER;
    GRANT ALL ON BOOKING to APP_OWNER;
    GRANT ALL ON CAR_CATEGORY to APP_OWNER;
    GRANT ALL ON CAR_LISTING to APP_OWNER;
    GRANT ALL ON CAR_REGISTRATION to APP_OWNER;
    GRANT ALL ON CITY to APP_OWNER;
    GRANT ALL ON COUNTRY to APP_OWNER;
    GRANT ALL ON EMPLOYEE to APP_OWNER;
    GRANT ALL ON PARKING to APP_OWNER;
    GRANT ALL ON ROLE to APP_OWNER;
    GRANT ALL ON STATE to APP_OWNER;
    GRANT ALL ON TRANSACTION to APP_OWNER;
    GRANT ALL ON USERS to APP_OWNER;
    
    GRANT ALL ON PCKG_CAR TO APP_OWNER;
    GRANT ALL ON PCKG_CUSTOMER TO APP_OWNER;
    GRANT ALL ON PCKG_INSURANCE TO APP_OWNER;
    GRANT ALL ON PCKG_SERVICE TO APP_OWNER;
    GRANT ALL ON PCKG_TRANSACT TO APP_OWNER; 
    GRANT ALL ON PCKG_VIOLATIONS TO APP_OWNER;
    GRANT ALL ON PCKG_UTILS TO APP_OWNER;

---------------------------------------
---         DEVELOPER
---------------------------------------
    GRANT CONNECT, CREATE SESSION TO DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON ADDRESS to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON BOOKING to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CAR_CATEGORY to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CAR_LISTING to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CAR_REGISTRATION to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON CITY to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON COUNTRY to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON EMPLOYEE to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON PARKING to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON STATE to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON TRANSACTION to DEVELOPER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON USERS to DEVELOPER;
    
    GRANT ALL ON PCKG_CAR TO DEVELOPER;
    GRANT ALL ON PCKG_CUSTOMER TO DEVELOPER;
    GRANT ALL ON PCKG_INSURANCE TO DEVELOPER;
    GRANT ALL ON PCKG_SERVICE TO DEVELOPER;
    GRANT ALL ON PCKG_TRANSACT TO DEVELOPER; 
    GRANT ALL ON PCKG_VIOLATIONS TO DEVELOPER;
    GRANT ALL ON PCKG_UTILS TO DEVELOPER;

---------------------------------------
---         TESTER
---------------------------------------
    GRANT CONNECT, CREATE SESSION to TESTER;
    GRANT SELECT, INSERT, UPDATE ON ADDRESS to TESTER;
    GRANT SELECT, INSERT, UPDATE ON BOOKING to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CAR_CATEGORY to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CAR_LISTING to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CAR_REGISTRATION to TESTER;
    GRANT SELECT, INSERT, UPDATE ON CITY to TESTER;
    GRANT SELECT, INSERT, UPDATE ON COUNTRY to TESTER;
    GRANT SELECT, INSERT, UPDATE ON EMPLOYEE to TESTER;
    GRANT SELECT, INSERT, UPDATE ON PARKING to TESTER;
    GRANT SELECT, INSERT, UPDATE ON STATE to TESTER;
    GRANT SELECT, INSERT, UPDATE ON TRANSACTION to TESTER;
    GRANT SELECT, INSERT, UPDATE ON USERS to TESTER;
    
    GRANT EXECUTE ON PCKG_CAR TO TESTER;
    GRANT EXECUTE ON PCKG_CUSTOMER TO TESTER;
    GRANT EXECUTE ON PCKG_INSURANCE TO TESTER;
    GRANT EXECUTE ON PCKG_SERVICE TO TESTER;
    GRANT EXECUTE ON PCKG_TRANSACT TO TESTER; 
    GRANT EXECUTE ON PCKG_VIOLATIONS TO TESTER;
    GRANT EXECUTE ON PCKG_UTILS TO TESTER;

---------------------------------------
---  ANALYST 
---------------------------------------
    GRANT  CONNECT, CREATE SESSION to ANALYST;

---------------------------------------
---         SERVICE
---------------------------------------
    GRANT CONNECT, CREATE SESSION to SERVICE;
    GRANT EXECUTE ON PCKG_CAR TO SERVICE;
    GRANT EXECUTE ON PCKG_CUSTOMER TO SERVICE;
    GRANT EXECUTE ON PCKG_INSURANCE TO SERVICE;
    GRANT EXECUTE ON PCKG_SERVICE TO SERVICE;
    GRANT EXECUTE ON PCKG_TRANSACT TO SERVICE; 
    GRANT EXECUTE ON PCKG_VIOLATIONS TO SERVICE;
    GRANT ALL ON PCKG_UTILS TO SERVICE;
    
----------------------------------------
--              USERS
----------------------------------------
    --APP_OWNER
    CREATE USER JARVIS IDENTIFIED BY Root1234567890; 
    --DEVELOPER
    CREATE USER HARRY IDENTIFIED BY Root1234567890;
    --TESTER
    CREATE USER PETER IDENTIFIED BY Root1234567890;
    --ANALYST
    CREATE USER TOM IDENTIFIED BY Root1234567890;
    --SERVICE
    CREATE USER ROOT IDENTIFIED BY Root1234567890;
    --AUDIT
    CREATE USER JESSY IDENTIFIED BY Root1234567890;



-----------------------------------------
-- ######################################
-----------------------------------------

-----------------------------------------
-- ROLES - USERS
-----------------------------------------

    GRANT APP_OWNER TO JARVIS;
    GRANT DEVELOPER TO HARRY;
    GRANT TESTER TO PETER;
    GRANT ANALYST TO TOM;
    GRANT SERVICE TO ROOT;

-----------------------------------------

    -- SELECT * FROM session_roles;
    
    -- SELECT * FROM user_role_privs;
    -- SELECT * FROM role_sys_privs where ROLE IN ('APP_OWNER','DEVELOPER','TESTER','ANALYST','SERVICE','SECURITY');
    -- SELECT * FROM role_tab_privs where ROLE IN ('APP_OWNER','DEVELOPER','TESTER','ANALYST','SERVICE','SECURITY');
    
    -- select * from ALL_TABLES where OWNER = 'ADMIN';
    -- select * from DBA_ROLE_PRIVS where grantee = 'ADMIN';
    
    -- SELECT * FROM dba_role_privs where GRANTED_ROLE IN ('ADMIN', 'APP_OWNER', 'DEVELOPER', 'TESTER', 'ANALYST', 'SERVICE', 'SECURITY');
