
  CREATE TABLE AUDIT_DATA   
   (  AUDIT_ID   NUMBER, 
	  USERNAME   VARCHAR2(50)  ,
      TABLE_NAME VARCHAR(50), 
	  AUDIT_DATE   TIMESTAMP (6) DEFAULT systimestamp, 
	  ACTION   VARCHAR2(25)  
   );



  ALTER TABLE AUDIT_DATA   MODIFY (  AUDIT_DATE   NOT NULL ENABLE);
  ALTER TABLE AUDIT_DATA   MODIFY (  ACTION   NOT NULL ENABLE);
  ALTER TABLE AUDIT_DATA   ADD PRIMARY KEY (  AUDIT_ID  );
  ALTER TABLE AUDIT_DATA   MODIFY (  USERNAME   NOT NULL ENABLE);
  ALTER TABLE AUDIT_DATA   MODIFY (  TABLE_NAME   NOT NULL ENABLE);



create sequence AUDIT_ID_SEQ 
    start with 1 
    increment by 1
    order;