CREATE TABLE AUDIT_DATA_BOOKING (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_COUNTRY (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_CITY (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_ADDRESS (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_EMPLOYEE (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_USER (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_CAR_LISTING (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_TRANSACTION (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_PARKING (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_CAR_CATEGORY (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_CAR_REGISTRATION (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_STATE (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);

CREATE TABLE AUDIT_DATA_ROLES (
  AUDIT_ID NUMBER,
  USERNAME VARCHAR2(50),
  TABLE_NAME VARCHAR(50),
  AUDIT_DATE TIMESTAMP (6) DEFAULT systimestamp,
  ACTION VARCHAR2(25)
);


ALTER TABLE AUDIT_DATA_BOOKING MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_BOOKING MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_BOOKING ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_BOOKING MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_BOOKING MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_COUNTRY MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_COUNTRY MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_COUNTRY ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_COUNTRY MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_COUNTRY MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_CITY MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CITY MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CITY ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_CITY MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CITY MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_ADDRESS MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_ADDRESS MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_ADDRESS ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_ADDRESS MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_ADDRESS MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_EMPLOYEE MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_EMPLOYEE MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_EMPLOYEE ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_EMPLOYEE MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_EMPLOYEE MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_USER MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_USER MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_USER ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_USER MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_USER MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_CAR_LISTING MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_LISTING MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_LISTING ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_CAR_LISTING MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_LISTING MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_TRANSACTION MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_TRANSACTION MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_TRANSACTION ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_TRANSACTION MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_TRANSACTION MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_PARKING MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_PARKING MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_PARKING ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_PARKING MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_PARKING MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_CAR_CATEGORY MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_CATEGORY MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_CATEGORY ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_CAR_CATEGORY MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_CATEGORY MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_CAR_REGISTRATION MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_REGISTRATION MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_REGISTRATION ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_CAR_REGISTRATION MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_CAR_REGISTRATION MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_STATE MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_STATE MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_STATE ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_STATE MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_STATE MODIFY (TABLE_NAME NOT NULL ENABLE);

ALTER TABLE AUDIT_DATA_ROLES MODIFY (AUDIT_DATE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_ROLES MODIFY (ACTION NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_ROLES ADD PRIMARY KEY (AUDIT_ID);
ALTER TABLE AUDIT_DATA_ROLES MODIFY (USERNAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA_ROLES MODIFY (TABLE_NAME NOT NULL ENABLE);



create sequence AUDIT_BOOKING_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_COUNTRY_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_CITY_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_EMPLOYEE_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_USER_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_CAR_LISTING_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_TRANSACTION_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_PARKING_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_CAR_CATEGORY_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_CAR_REGISTRATION_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_STATE_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_ADDRESS_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_ROLE_ID_SEQ start with 1 increment by 1 order;