-- BEGIN
--   FOR rec IN
--     (
--       SELECT
--         sequence_name
--       FROM
--         user_sequences
--     )
--   LOOP
--     EXECUTE immediate 'DROP SEQUENCE  '||rec.sequence_name;
--   END LOOP;
-- END;
-- /

set serveroutput on;



/*
    PROCEDURE FOR CHECKING AND DROPPING THE SEQUENCE IF IT EXISTS
*/
CREATE OR REPLACE PROCEDURE CHECKANDREMOVESEQEUENCE(SEQUENCENAME IN VARCHAR2) IS
  c Number;
BEGIN
  SELECT count(*) INTO c FROM USER_SEQUENCES WHERE SEQUENCE_NAME = SEQUENCENAME;
  IF c = 1 THEN
    EXECUTE IMMEDIATE ('DROP SEQUENCE '|| SEQUENCENAME);
  END IF;
END;
/

EXECUTE CHECKANDREMOVESEQEUENCE('ADDRESS_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('BOOKING_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('CAR_CATEGORY_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('CAR_LISTING_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('CAR_REGISTRATION_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('CITY_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('COUNTRY_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('EMPLOYEE_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('PARKING_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('ROLE_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('STATE_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('TRANSACTION_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('USERS_ID_SEQ');

CREATE SEQUENCE ADDRESS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE BOOKING_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE CAR_CATEGORY_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE CAR_LISTING_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE CAR_REGISTRATION_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE CITY_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE COUNTRY_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE EMPLOYEE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE PARKING_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE ROLE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE STATE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE TRANSACTION_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;

CREATE SEQUENCE USERS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    ORDER;



------------------AUDIT------------------------------

EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_BOOKING_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_COUNTRY_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_CITY_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_EMPLOYEE_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_USER_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_CAR_LISTING_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_TRANSACTION_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_PARKING_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_CAR_CATEGORY_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_CAR_REGISTRATION_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_STATE_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_ADDRESS_ID_SEQ');
EXECUTE CHECKANDREMOVESEQEUENCE('AUDIT_ROLE_ID_SEQ');


create sequence AUDIT_BOOKING_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_COUNTRY_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_CITY_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_EMPLOYEE_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_USER_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_CAR_LISTING_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_TRANSACTION_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_PARKING_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_CAR_CATEGORY_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_CAR_REGISTRATION_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_STATE_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_ADDRESS_ID_SEQ start with 1 increment by 1 order;
create sequence AUDIT_ROLE_ID_SEQ start with 1 increment by 1 order;