SET SERVEROUTPUT ON;

CREATE OR REPLACE EDITIONABLE PACKAGE PCKG_PARKING_EXT AS

    PROCEDURE INSERT_PARKING_EXT(
        vADDRESS_LINE_1 IN ADDRESS.ADDRESS_LINE_1%type,
        vADDRESS_LINE_2 IN ADDRESS.ADDRESS_LINE_2%type,
        vZIP_CODE IN ADDRESS.ZIPCODE%type,
        vCITY_NAME IN CITY.CITY_NAME%TYPE,
        vSTATE_NAME IN STATE.STATE_NAME%TYPE,
        vCOUNTRY_NAME IN COUNTRY.COUNTRY_NAME%TYPE);

END PCKG_PARKING_EXT;
/

CREATE OR REPLACE EDITIONABLE PACKAGE BODY PCKG_PARKING_EXT AS

    PROCEDURE INSERT_PARKING_EXT(
        vADDRESS_LINE_1 IN ADDRESS.ADDRESS_LINE_1%type,
        vADDRESS_LINE_2 IN ADDRESS.ADDRESS_LINE_2%type,
        vZIP_CODE IN ADDRESS.ZIPCODE%type,
        vCITY_NAME IN CITY.CITY_NAME%TYPE,
        vSTATE_NAME IN STATE.STATE_NAME%TYPE,
        vCOUNTRY_NAME IN COUNTRY.COUNTRY_NAME%TYPE) AS
        EXISTING_ADDRESS_COUNT NUMBER(5);
        vADDRESS_ID ADDRESS.ADDRESS_ID%type;
    BEGIN
        -- Check if the address already exists in address table as parking type
        -- IF address exists, get ID and check if there exists parking id with that address ID
        -- IF address doesn't exist, create one using pkg_address and Create parking id with the created address_id
        BEGIN
            SELECT COUNT(*) INTO EXISTING_ADDRESS_COUNT FROM ADDRESS WHERE UPPER(ADDRESS_LINE_1) = UPPER(TRIM(vADDRESS_LINE_1)) AND ADDRESS_TYPE = 'PARKING';
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    EXISTING_ADDRESS_COUNT := 0;
        END;
        IF EXISTING_ADDRESS_COUNT < 1 THEN
            -- TRY INSERTING ADDRESS
            PKG_ADDRESS.INSERT_ADDRESS(UPPER(vADDRESS_LINE_1), UPPER(vADDRESS_LINE_2), vZIP_CODE, UPPER(vCITY_NAME), UPPER(vSTATE_NAME), 'PARKING', UPPER(vCOUNTRY_NAME));
        END IF;
        BEGIN
            SELECT COUNT(*) INTO EXISTING_ADDRESS_COUNT FROM ADDRESS WHERE UPPER(ADDRESS_LINE_1) = UPPER(TRIM(vADDRESS_LINE_1)) AND ADDRESS_TYPE = 'PARKING';
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    EXISTING_ADDRESS_COUNT := 0;
        END;
        IF EXISTING_ADDRESS_COUNT > 0 THEN
            SELECT ADDRESS_ID INTO vADDRESS_ID FROM ADDRESS WHERE UPPER(ADDRESS_LINE_1) = UPPER(TRIM(vADDRESS_LINE_1)) AND ADDRESS_TYPE = 'PARKING';
            -- TRY INSERTING PARKING
            PCKG_PARKING.INSERT_PARKING(vADDRESS_ID);
        ELSE
            dbms_output.put_line('ADDRESS INSERT FAILED, PLEASE CHECK!!!');
        END IF;
        -- EXCEPTION
    END INSERT_PARKING_EXT;

END PCKG_PARKING_EXT;
/

--EXECUTE PCKG_PARKING_EXT.INSERT_PARKING_EXT('16 SHEPHERD AVE', 'APT 2', '02115', 'BOSTON', 'MA', 'USA');